namespace SME.Sondagem.Aplicacao.Interfaces.Questionario.Relatorio.Exportacao;

public interface IExportarSondagemRelatorioConsolidadoBimestreUseCase : IExportarSondagemRelatorioConsolidadoUseCase
{
}
