using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SME.Sondagem.Dados.Migrations
{
    /// <inheritdoc />
    public partial class AdicionarSemestre : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS semestre (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    cod_semestre_eol integer NOT NULL,
                    descricao character varying(50),
                    alterado_em timestamp with time zone,
                    alterado_por character varying(200),
                    alterado_rf character varying(200),
                    criado_em timestamp with time zone NOT NULL,
                    criado_por character varying(200) NOT NULL,
                    criado_rf character varying(200) NOT NULL,
                    excluido boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT pk_semestre PRIMARY KEY (id)
                );

                ALTER TABLE resposta_aluno ADD COLUMN IF NOT EXISTS semestre_id integer;

                CREATE INDEX IF NOT EXISTS ""IX_resposta_aluno_semestre_id"" ON resposta_aluno (semestre_id);

                DO $$ BEGIN
                    ALTER TABLE resposta_aluno ADD CONSTRAINT fk_semestre_resposta_aluno
                        FOREIGN KEY (semestre_id) REFERENCES semestre(id);
                EXCEPTION WHEN duplicate_object THEN NULL;
                END $$;

                INSERT INTO semestre (id, cod_semestre_eol, descricao, criado_em, criado_por, criado_rf, excluido)
                VALUES
                    (1, 1, '1° semestre', '2025-01-09 11:00:00+00', 'SISTEMA', 'SISTEMA', FALSE),
                    (2, 2, '2° semestre', '2025-01-09 11:00:00+00', 'SISTEMA', 'SISTEMA', FALSE)
                ON CONFLICT (id) DO NOTHING;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_semestre_resposta_aluno",
                table: "resposta_aluno");

            migrationBuilder.DropTable(
                name: "semestre");

            migrationBuilder.DropIndex(
                name: "IX_resposta_aluno_semestre_id",
                table: "resposta_aluno");

            migrationBuilder.DropColumn(
                name: "semestre_id",
                table: "resposta_aluno");
        }
    }
}
