// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Sondagem.Dados.Contexto;

#nullable disable

namespace SME.Sondagem.Dados.Migrations
{
    [DbContext(typeof(SondagemDbContext))]
    partial class SondagemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int?>("CorId")
                        .HasColumnType("integer")
                        .HasColumnName("cor_id");

                    b.Property<string>("CorNome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor_nome");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<int?>("DeficienciaId")
                        .HasColumnType("integer")
                        .HasColumnName("deficiencia_id");

                    b.Property<string>("DeficienciaNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deficiencia_nome");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<bool>("IsAee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_aee");

                    b.Property<bool>("IsPap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pap");

                    b.Property<bool>("IsPcd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pcd");

                    b.Property<string>("NomeAluno")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_aluno");

                    b.Property<string>("RaAluno")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ra_aluno");

                    b.Property<int?>("RacaId")
                        .HasColumnType("integer")
                        .HasColumnName("raca_id");

                    b.Property<string>("RacaNome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("raca_nome");

                    b.HasKey("Id")
                        .HasName("pk_aluno");

                    b.HasIndex("RaAluno")
                        .IsUnique()
                        .HasDatabaseName("uk_aluno_ra")
                        .HasFilter("ra_aluno IS NOT NULL");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<string>("Administrador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("administrador");

                    b.Property<long>("Chave")
                        .HasColumnType("bigint")
                        .HasColumnName("chave");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entidade");

                    b.Property<Guid?>("Perfil")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil");

                    b.Property<string>("RF")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rf");

                    b.Property<string>("Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Chave")
                        .HasDatabaseName("ix_auditoria_chave");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_auditoria_data");

                    b.HasIndex("Entidade")
                        .HasDatabaseName("ix_auditoria_entidade");

                    b.HasIndex("Entidade", "Chave")
                        .HasDatabaseName("ix_auditoria_entidade_chave");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.AuditoriaDetalhe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuditoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("auditoria_id");

                    b.Property<string>("NomePropriedade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_propriedade");

                    b.Property<string>("ValorAntigo")
                        .HasColumnType("text")
                        .HasColumnName("valor_antigo");

                    b.Property<string>("ValorNovo")
                        .HasColumnType("text")
                        .HasColumnName("valor_novo");

                    b.HasKey("Id")
                        .HasName("pk_auditoria_detalhe");

                    b.HasIndex("AuditoriaId")
                        .HasDatabaseName("ix_auditoria_detalhe_auditoria_id");

                    b.HasIndex("NomePropriedade")
                        .HasDatabaseName("ix_auditoria_detalhe_nome_propriedade");

                    b.ToTable("auditoria_detalhe", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Bimestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("CodBimestreEnsinoEol")
                        .HasColumnType("integer")
                        .HasColumnName("cod_bimestre_ensino_eol");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_bimestre");

                    b.HasIndex("CodBimestreEnsinoEol")
                        .IsUnique()
                        .HasDatabaseName("uk_bimestre_cod_eol");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("uk_bimestre_desc");

                    b.ToTable("bimestre", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.ComponenteCurricular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("CodigoEol")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_eol");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<string>("Modalidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modalidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_componente_curricular");

                    b.HasIndex("Nome", "Ano", "Modalidade")
                        .IsUnique()
                        .HasDatabaseName("uk_componente_nome_ano_modalidade");

                    b.ToTable("componente_curricular", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Proficiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("ComponenteCurricularId")
                        .HasColumnType("integer")
                        .HasColumnName("componente_curricular_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_proficiencia");

                    b.HasIndex("ComponenteCurricularId");

                    b.HasIndex("Nome", "ComponenteCurricularId")
                        .IsUnique()
                        .HasDatabaseName("uk_proficiencia_nome_componente");

                    b.ToTable("proficiencia", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.GrupoQuestoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_grupo_questoes");

                    b.ToTable("grupo_questoes", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<string>("CorFundo")
                        .HasColumnType("text")
                        .HasColumnName("cor_fundo");

                    b.Property<string>("CorTexto")
                        .HasColumnType("text")
                        .HasColumnName("cor_texto");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<string>("DescricaoOpcaoResposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao_opcao_resposta");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<string>("Legenda")
                        .HasColumnType("text")
                        .HasColumnName("legenda");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id")
                        .HasName("pk_opcao_resposta");

                    b.HasIndex("DescricaoOpcaoResposta")
                        .IsUnique()
                        .HasDatabaseName("uk_opcao_resposta_desc");

                    b.ToTable("opcao_resposta", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<int>("Dimensao")
                        .HasColumnType("integer")
                        .HasColumnName("dimensao");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<int?>("GrupoQuestoesId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_questoes_id");

                    b.Property<string>("Mascara")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mascara");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeComponente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_componente");

                    b.Property<bool>("Obrigatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("obrigatorio");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Opcionais")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("opcionais");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("PlaceHolder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("place_holder");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("integer")
                        .HasColumnName("questionario_id");

                    b.Property<bool>("SomenteLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("somente_leitura");

                    b.Property<int?>("Tamanho")
                        .HasColumnType("integer")
                        .HasColumnName("tamanho");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_questao");

                    b.HasIndex("GrupoQuestoesId");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("questao", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.QuestaoOpcaoResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<int>("OpcaoRespostaId")
                        .HasColumnType("integer")
                        .HasColumnName("opcao_resposta_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer")
                        .HasColumnName("questao_id");

                    b.HasKey("Id")
                        .HasName("pk_questao_opcao_resposta");

                    b.HasIndex("OpcaoRespostaId");

                    b.HasIndex("QuestaoId", "OpcaoRespostaId")
                        .IsUnique()
                        .HasDatabaseName("uk_questao_opcao");

                    b.ToTable("questao_opcao_resposta", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("integer")
                        .HasColumnName("ano_letivo");

                    b.Property<int?>("BimestreId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponenteCurricularId")
                        .HasColumnType("integer")
                        .HasColumnName("componente_curricular_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<int?>("ModalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("ProficienciaId")
                        .HasColumnType("integer")
                        .HasColumnName("proficiencia_id");

                    b.Property<int?>("SerieAno")
                        .HasColumnType("integer")
                        .HasColumnName("serie_ano");

                    b.Property<int>("SondagemId")
                        .HasColumnType("integer")
                        .HasColumnName("sondagem_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_questionario");

                    b.HasIndex("BimestreId");

                    b.HasIndex("ComponenteCurricularId");

                    b.HasIndex("ProficienciaId");

                    b.HasIndex("SondagemId");

                    b.ToTable("questionario", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Sondagem.RespostaAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<int?>("BimestreId")
                        .HasColumnType("integer")
                        .HasColumnName("bimestre_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<DateTime>("DataResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resposta")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<int?>("OpcaoRespostaId")
                        .HasColumnType("integer")
                        .HasColumnName("opcao_resposta_id");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer")
                        .HasColumnName("questao_id");

                    b.Property<int>("SondagemId")
                        .HasColumnType("integer")
                        .HasColumnName("sondagem_id");

                    b.HasKey("Id")
                        .HasName("pk_resposta_aluno");

                    b.HasIndex("BimestreId");

                    b.HasIndex("OpcaoRespostaId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("SondagemId", "AlunoId", "QuestaoId", "BimestreId")
                        .IsUnique()
                        .HasDatabaseName("uk_resposta_sondagem_aluno_questao");

                    b.ToTable("resposta_aluno", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Sondagem.Sondagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<DateTime>("DataAplicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aplicacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.HasKey("Id")
                        .HasName("pk_sondagem");

                    b.ToTable("sondagem", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Sondagem.SondagemPeriodoBimestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("BimestreId")
                        .HasColumnType("integer")
                        .HasColumnName("bimestre_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<int>("SondagemId")
                        .HasColumnType("integer")
                        .HasColumnName("sondagem_id");

                    b.HasKey("Id")
                        .HasName("pk_sondagem_periodo_bimestre");

                    b.HasIndex("BimestreId");

                    b.HasIndex("SondagemId");

                    b.ToTable("sondagem_periodo_bimestre", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.AuditoriaDetalhe", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Auditoria", "Auditoria")
                        .WithMany("Detalhes")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_detalhe_auditoria");

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Proficiencia", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.ComponenteCurricular", "ComponenteCurricular")
                        .WithMany("Proficiencias")
                        .HasForeignKey("ComponenteCurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proficiencia_componente");

                    b.Navigation("ComponenteCurricular");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questao", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.GrupoQuestoes", "GrupoQuestoes")
                        .WithMany("Questoes")
                        .HasForeignKey("GrupoQuestoesId")
                        .HasConstraintName("fk_questao_grupo");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", "Questionario")
                        .WithMany("Questoes")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questao_questionario");

                    b.Navigation("GrupoQuestoes");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.QuestaoOpcaoResposta", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", "OpcaoResposta")
                        .WithMany("QuestaoOpcoes")
                        .HasForeignKey("OpcaoRespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questao_opcao_opcao");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Questao", "Questao")
                        .WithMany("QuestaoOpcoes")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questao_opcao_questao");

                    b.Navigation("OpcaoResposta");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Bimestre", null)
                        .WithMany("Questionarios")
                        .HasForeignKey("BimestreId");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.ComponenteCurricular", "ComponenteCurricular")
                        .WithMany("Questionarios")
                        .HasForeignKey("ComponenteCurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionario_componente");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Proficiencia", "Proficiencia")
                        .WithMany("Questionarios")
                        .HasForeignKey("ProficienciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionario_proficiencia");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Sondagem.Sondagem", "Sondagem")
                        .WithMany("Questionarios")
                        .HasForeignKey("SondagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sondagem_questionario");

                    b.Navigation("ComponenteCurricular");

                    b.Navigation("Proficiencia");

                    b.Navigation("Sondagem");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Sondagem.RespostaAluno", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Bimestre", "Bimestre")
                        .WithMany("RespostaAlunos")
                        .HasForeignKey("BimestreId")
                        .HasConstraintName("fk_bimestre_resposta_aluno");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", "OpcaoResposta")
                        .WithMany("Respostas")
                        .HasForeignKey("OpcaoRespostaId")
                        .HasConstraintName("fk_resposta_opcao");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Questao", "Questao")
                        .WithMany("Respostas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resposta_questao");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Sondagem.Sondagem", "Sondagem")
                        .WithMany("Respostas")
                        .HasForeignKey("SondagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resposta_sondagem");

                    b.Navigation("Bimestre");

                    b.Navigation("OpcaoResposta");

                    b.Navigation("Questao");

                    b.Navigation("Sondagem");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Sondagem.SondagemPeriodoBimestre", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Bimestre", "Bimestre")
                        .WithMany("PeriodosBimestre")
                        .HasForeignKey("BimestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bimestre_sondagem_periodo_bimestre");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Sondagem.Sondagem", "Sondagem")
                        .WithMany("PeriodosBimestre")
                        .HasForeignKey("SondagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sondagem_sondagem_periodo_bimestre");

                    b.Navigation("Bimestre");

                    b.Navigation("Sondagem");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Auditoria", b =>
                {
                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Bimestre", b =>
                {
                    b.Navigation("PeriodosBimestre");

                    b.Navigation("Questionarios");

                    b.Navigation("RespostaAlunos");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.ComponenteCurricular", b =>
                {
                    b.Navigation("Proficiencias");

                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Proficiencia", b =>
                {
                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.GrupoQuestoes", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", b =>
                {
                    b.Navigation("QuestaoOpcoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questao", b =>
                {
                    b.Navigation("QuestaoOpcoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Sondagem.Sondagem", b =>
                {
                    b.Navigation("PeriodosBimestre");

                    b.Navigation("Questionarios");

                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
