// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SME.Sondagem.Dados.Contexto;

#nullable disable

namespace SME.Sondagem.Dados.Migrations
{
    [DbContext(typeof(SondagemDbContext))]
    partial class SondagemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int?>("CorId")
                        .HasColumnType("integer")
                        .HasColumnName("cor_id");

                    b.Property<string>("CorNome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor_nome");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<int?>("DeficienciaId")
                        .HasColumnType("integer")
                        .HasColumnName("deficiencia_id");

                    b.Property<string>("DeficienciaNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deficiencia_nome");

                    b.Property<bool>("IsAee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_aee");

                    b.Property<bool>("IsPap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pap");

                    b.Property<bool>("IsPcd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pcd");

                    b.Property<string>("NomeAluno")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_aluno");

                    b.Property<string>("RaAluno")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ra_aluno");

                    b.Property<int?>("RacaId")
                        .HasColumnType("integer")
                        .HasColumnName("raca_id");

                    b.Property<string>("RacaNome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("raca_nome");

                    b.HasKey("Id")
                        .HasName("pk_aluno");

                    b.HasIndex("RaAluno")
                        .IsUnique()
                        .HasDatabaseName("uk_aluno_ra")
                        .HasFilter("ra_aluno IS NOT NULL");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Ciclo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("CodCicloEnsinoEol")
                        .HasColumnType("integer")
                        .HasColumnName("cod_ciclo_ensino_eol");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<string>("DescCiclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("desc_ciclo");

                    b.HasKey("Id")
                        .HasName("pk_ciclo");

                    b.HasIndex("CodCicloEnsinoEol")
                        .IsUnique()
                        .HasDatabaseName("uk_ciclo_cod_eol");

                    b.HasIndex("DescCiclo")
                        .IsUnique()
                        .HasDatabaseName("uk_ciclo_desc");

                    b.ToTable("ciclo", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.ComponenteCurricular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<string>("Modalidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modalidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_componente_curricular");

                    b.HasIndex("Nome", "Ano", "Modalidade")
                        .IsUnique()
                        .HasDatabaseName("uk_componente_nome_ano_modalidade");

                    b.ToTable("componente_curricular", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.GrupoQuestoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_grupo_questoes");

                    b.ToTable("grupo_questoes", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<string>("DescricaoOpcaoResposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao_opcao_resposta");

                    b.Property<string>("Legenda")
                        .HasColumnType("text")
                        .HasColumnName("legenda");

                    b.HasKey("Id")
                        .HasName("pk_opcao_resposta");

                    b.HasIndex("DescricaoOpcaoResposta")
                        .IsUnique()
                        .HasDatabaseName("uk_opcao_resposta_desc");

                    b.ToTable("opcao_resposta", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Proficiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("ComponenteCurricularId")
                        .HasColumnType("integer")
                        .HasColumnName("componente_curricular_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_proficiencia");

                    b.HasIndex("ComponenteCurricularId");

                    b.HasIndex("Nome", "ComponenteCurricularId")
                        .IsUnique()
                        .HasDatabaseName("uk_proficiencia_nome_componente");

                    b.ToTable("proficiencia", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<int>("Dimensao")
                        .HasColumnType("integer")
                        .HasColumnName("dimensao");

                    b.Property<int?>("GrupoQuestoesId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_questoes_id");

                    b.Property<string>("Mascara")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mascara");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeComponente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_componente");

                    b.Property<bool>("Obrigatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("obrigatorio");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Opcionais")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("opcionais");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("PlaceHolder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("place_holder");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("integer")
                        .HasColumnName("questionario_id");

                    b.Property<bool>("SomenteLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("somente_leitura");

                    b.Property<int?>("Tamanho")
                        .HasColumnType("integer")
                        .HasColumnName("tamanho");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_questao");

                    b.HasIndex("GrupoQuestoesId");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("questao", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.QuestaoOpcaoResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<int>("OpcaoRespostaId")
                        .HasColumnType("integer")
                        .HasColumnName("opcao_resposta_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer")
                        .HasColumnName("questao_id");

                    b.HasKey("Id")
                        .HasName("pk_questao_opcao_resposta");

                    b.HasIndex("OpcaoRespostaId");

                    b.HasIndex("QuestaoId", "OpcaoRespostaId")
                        .IsUnique()
                        .HasDatabaseName("uk_questao_opcao");

                    b.ToTable("questao_opcao_resposta", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("integer")
                        .HasColumnName("ano_letivo");

                    b.Property<int>("CicloId")
                        .HasColumnType("integer")
                        .HasColumnName("ciclo_id");

                    b.Property<int>("ComponenteCurricularId")
                        .HasColumnType("integer")
                        .HasColumnName("componente_curricular_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<int?>("DreId")
                        .HasColumnType("integer")
                        .HasColumnName("dre_id");

                    b.Property<string>("DreNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dre_nome");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<string>("ModalidadeDesc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modalidade_desc");

                    b.Property<int?>("ModalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("ProficienciaId")
                        .HasColumnType("integer")
                        .HasColumnName("proficiencia_id");

                    b.Property<int?>("SerieAno")
                        .HasColumnType("integer")
                        .HasColumnName("serie_ano");

                    b.Property<string>("SerieAnoNome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serie_ano_nome");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.Property<string>("TurmaNome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("turma_nome");

                    b.Property<int?>("UeId")
                        .HasColumnType("integer")
                        .HasColumnName("ue_id");

                    b.Property<string>("UeNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ue_nome");

                    b.HasKey("Id")
                        .HasName("pk_questionario");

                    b.HasIndex("CicloId");

                    b.HasIndex("ComponenteCurricularId");

                    b.HasIndex("ProficienciaId");

                    b.ToTable("questionario", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.RespostaAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<DateTime>("DataResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resposta")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OpcaoRespostaId")
                        .HasColumnType("integer")
                        .HasColumnName("opcao_resposta_id");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("integer")
                        .HasColumnName("questao_id");

                    b.Property<int>("SondagemId")
                        .HasColumnType("integer")
                        .HasColumnName("sondagem_id");

                    b.HasKey("Id")
                        .HasName("pk_resposta_aluno");

                    b.HasIndex("AlunoId");

                    b.HasIndex("OpcaoRespostaId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("SondagemId", "AlunoId", "QuestaoId")
                        .IsUnique()
                        .HasDatabaseName("uk_resposta_sondagem_aluno_questao");

                    b.ToTable("resposta_aluno", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Sondagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("AlteradoRF")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alterado_rf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoRF")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criado_rf");

                    b.Property<DateTime>("DataAplicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aplicacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("integer")
                        .HasColumnName("questionario_id");

                    b.HasKey("Id")
                        .HasName("pk_sondagem");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("sondagem", (string)null);
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Proficiencia", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.ComponenteCurricular", "ComponenteCurricular")
                        .WithMany("Proficiencias")
                        .HasForeignKey("ComponenteCurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proficiencia_componente");

                    b.Navigation("ComponenteCurricular");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questao", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.GrupoQuestoes", "GrupoQuestoes")
                        .WithMany("Questoes")
                        .HasForeignKey("GrupoQuestoesId")
                        .HasConstraintName("fk_questao_grupo");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", "Questionario")
                        .WithMany("Questoes")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questao_questionario");

                    b.Navigation("GrupoQuestoes");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.QuestaoOpcaoResposta", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", "OpcaoResposta")
                        .WithMany("QuestaoOpcoes")
                        .HasForeignKey("OpcaoRespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questao_opcao_opcao");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Questao", "Questao")
                        .WithMany("QuestaoOpcoes")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questao_opcao_questao");

                    b.Navigation("OpcaoResposta");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Ciclo", "Ciclo")
                        .WithMany("Questionarios")
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionario_ciclo");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.ComponenteCurricular", "ComponenteCurricular")
                        .WithMany("Questionarios")
                        .HasForeignKey("ComponenteCurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionario_componente");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Proficiencia", "Proficiencia")
                        .WithMany("Questionarios")
                        .HasForeignKey("ProficienciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionario_proficiencia");

                    b.Navigation("Ciclo");

                    b.Navigation("ComponenteCurricular");

                    b.Navigation("Proficiencia");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.RespostaAluno", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Aluno", "Aluno")
                        .WithMany("Respostas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resposta_aluno");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", "OpcaoResposta")
                        .WithMany("Respostas")
                        .HasForeignKey("OpcaoRespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resposta_opcao");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Questao", "Questao")
                        .WithMany("Respostas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resposta_questao");

                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Sondagem", "Sondagem")
                        .WithMany("Respostas")
                        .HasForeignKey("SondagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resposta_sondagem");

                    b.Navigation("Aluno");

                    b.Navigation("OpcaoResposta");

                    b.Navigation("Questao");

                    b.Navigation("Sondagem");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Sondagem", b =>
                {
                    b.HasOne("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", "Questionario")
                        .WithMany("Sondagens")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sondagem_questionario");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Aluno", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Ciclo", b =>
                {
                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.ComponenteCurricular", b =>
                {
                    b.Navigation("Proficiencias");

                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.GrupoQuestoes", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.OpcaoResposta", b =>
                {
                    b.Navigation("QuestaoOpcoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Proficiencia", b =>
                {
                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questao", b =>
                {
                    b.Navigation("QuestaoOpcoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Questionario", b =>
                {
                    b.Navigation("Questoes");

                    b.Navigation("Sondagens");
                });

            modelBuilder.Entity("SME.Sondagem.Dominio.Entidades.Questionario.Sondagem", b =>
                {
                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
